version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app-staging
    env_file:
      - .env.staging
    environment:
      - NODE_ENV=staging
    networks:
      - staging-network
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

  nginx:
    image: nginx:alpine
    container_name: nginx-staging
    ports:
      - "8080:80"
    volumes:
      - ./nginx/staging.conf:/etc/nginx/conf.d/default.conf
    networks:
      - staging-network
    depends_on:
      - app

networks:
  staging-network:
    name: staging-network
    driver: bridge
