version: '3.8'

services:
  # Staging Environment
  staging-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app-staging
    environment:
      - NODE_ENV=staging
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

  staging-nginx:
    image: nginx:alpine
    container_name: nginx-staging
    ports:
      - "8080:80"
    volumes:
      - ./nginx/staging.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - staging-app

  # Production Environment
  prod-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: node-app-prod
    environment:
      - NODE_ENV=production
      - PORT=3000
    expose:
      - "3000"
    command: npm start

  prod-nginx:
    image: nginx:alpine
    container_name: nginx-prod
    ports:
      - "80:80"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - prod-app
