FROM node:22.14.0

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Bundle app source
COPY . .

# Expose port
EXPOSE 3000

# Use node directly in production, not nodemon
CMD ["node", "index.js"]
