version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: node-app-prod
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    networks:
      - prod-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  nginx:
    image: nginx:alpine
    container_name: nginx-prod
    ports:
      - "8081:80"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
    networks:
      - prod-network
    depends_on:
      - app
    restart: unless-stopped

networks:
  prod-network:
    name: prod-network
    driver: bridge
